name: C/C++ CI

on: [push]

jobs:
  build-native:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu, macos, windows]
    steps:
    - name: "macOS: Setup"
      if: matrix.os == 'macos'
      run: brew install autoconf automake libtool
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build (Native)
      run: make
    - name: "*nix: Stash"
      if: matrix.os != 'windows'
      uses: actions/upload-artifact@v1
      with:
        name: helloworld-${{ matrix.os }}
        path: helloworld
    - name: "Windows: Stash"
      if: matrix.os == 'windows'
      uses: actions/upload-artifact@v1
      with:
        name: helloworld-${{ matrix.os }}
        path: helloworld.exe
  build-cross:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        os: [dos32, c64]
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "DOS32: Build"
      if: matrix.os == 'dos32'
      run: |
        wget -q https://github.com/andrewwutw/build-djgpp/releases/download/v2.8/djgpp-linux64-gcc720.tar.bz2
        tar -xf djgpp-linux64-gcc720.tar.bz2
        export PATH=${PWD}/djgpp/bin/:$PATH
        make PREFIX="i586-pc-msdosdjgpp-" MAIN="HELLO.EXE"
        echo "##### Packaging #####"
        mkdir temp-dist-dir
        mkdir temp-extract-dir
        cd temp-extract-dir
        wget -q http://sandmann.dotster.com/cwsdpmi/csdpmi7b.zip
        unzip -q csdpmi7b.zip
        cd ..
        mv HELLO.EXE temp-dist-dir/HELLO.EXE
        mv temp-extract-dir/bin/CWSDPMI.EXE temp-dist-dir/CWSDPMI.EXE
    - name: "C64: Build"
      if: matrix.os == 'c64'
      run: |
        sudo apt install cc65
        export PATH=${PWD}/djgpp/bin/:$PATH
        make CC="cl65" COPTS="-t c64"
        mkdir temp-dist-dir
        mv helloworld temp-dist-dir/helloworld.c64
    - name: List Directory Structure
      run: ls
    - name: "Stash"
      uses: actions/upload-artifact@v1
      with:
        name: helloworld-${{ matrix.os }}
        path: temp-dist-dir
