name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest] #, windows-latest
        true-os: [native, dos]
        exclude:
          - os: windows-latest
            true-os: dos
          - os: macos-latest
            true-os: dos
    steps:
    - name: DOS Setup
      if: matrix.true-os == 'dos'
      run: |
        wget -q https://github.com/andrewwutw/build-djgpp/releases/download/v2.8/djgpp-linux64-gcc720.tar.bz2
        tar -xf djgpp-linux64-gcc720.tar.bz2
        export BASE_DIR=${PWD}/djgpp
        export PATH=$BASE_DIR/bin/:$PATH
        export GCC_EXEC_PREFIX=$BASE_DIR/lib/gcc/
        echo "PATH: $PATH"
        i586-pc-msdosdjgpp-gcc --version
    - name: Mac Setup
      if: matrix.os == 'macos-latest'
      run: brew install autoconf automake libtool
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build (Native)
      if: matrix.true-os == 'native'
      run: make
    - name: Build (DOS)
      if: matrix.true-os == 'dos'
      run: make PREFIX="i586-pc-msdosdjgpp-"
    - name: List Directory Structure
      run: ls -l
    - name: Stash (Native)
      if: matrix.true-os == 'native'
      uses: actions/upload-artifact@v1
      with:
        name: helloworld-${{ matrix.os }}
        path: helloworld
    - name: Stash (Non-Native)
      if: matrix.true-os == 'dos'
      uses: actions/upload-artifact@v1
      with:
        name: helloworld-${{ matrix.true-os }}
        path: helloworld
