name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
#       true-os: [native]
        true-os: [native, dos]
        exclude:
          - os: windows-latest
            true-os: dos
          - os: macos-latest
            true-os: dos
    steps:
    - name: DOS test
      run: echo "This is building for DOS."
      if: matrix.true-os == 'dos'
    - name: Checkout
      uses: actions/checkout@v1
      if: matrix.true-os == 'native'
    - name: List Directories
      run: ls
      if: matrix.true-os == 'native'
    - name: automake stuff
      if: matrix.true-os == 'native'
      run: aclocal
      run: autoconf
      run: automake --add-missing
    - name: configure
      run: ./configure
      if: matrix.true-os == 'native'
    - name: make
      run: make
      if: matrix.true-os == 'native'
    - name: make distcheck
      run: make distcheck
      if: matrix.true-os == 'native'
    - name: Release
      uses: anton-yurchenko/git-release@v3.0.1
      if: matrix.true-os == 'native'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DRAFT_RELEASE: "false"
        PRE_RELEASE: "true"
        CHANGELOG_FILE: "CHANGELOG.md"
        ALLOW_EMPTY_CHANGELOG: "true"
        ALLOW_TAG_PREFIX: "true"
      with:
        args: |
            build/darwin-amd64.zip
            build/linux-amd64.zip
            build/windows-amd64.zip
