name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest] #, windows-latest
        true-os: [native, dos]
        exclude:
          - os: windows-latest
            true-os: dos
          - os: macos-latest
            true-os: dos
    steps:
    - name: DOS Setup
      if: matrix.true-os == 'dos'
      run: |
        wget https://github.com/andrewwutw/build-djgpp/releases/download/v2.8/djgpp-linux64-gcc720.tar.bz2
        tar -xvf djgpp-linux64-gcc720.tar.bz2
        echo "### PATH ###"
        echo $PATH
        echo "### $PWD/djgpp/bin ###"
        ls -l $PWD/djgpp/bin
#       tar -xvf djgpp-linux64-gcc720.tar.bz2 -C /usr/local/
#        echo "### /usr/local/ ###"
#        ls -l /usr/local/
#       tar -xvf djgpp-linux64-gcc720.tar.bz2
#       export PATH=$PWD/djgpp/bin/:$PATH
    - name: Mac Setup
      if: matrix.os == 'macos-latest'
      run: |
        brew install autoconf automake libtool
    - name: Checkout
#     if: matrix.true-os == 'native'
      uses: actions/checkout@v1
    - name: Automake
#     if: matrix.true-os == 'native'
      run: |
        aclocal
        autoconf
        automake --add-missing
    - name: Configure (Native)
      if: matrix.true-os == 'native'
      run: ./configure
    - name: Configure (DOS)
      if: matrix.true-os == 'dos'
#     run: ./configure --build x86_64-pc-linux-gnu --host i586-pc-msdosdjgpp
      run: ./configure --host i586-pc-msdosdjgpp
    - name: make
#     if: matrix.true-os == 'native'
      run: |
        make
#       make distcheck
    - name: List Directory Structure
      run: ls -l
    - name: Stash (Native)
      if: matrix.true-os == 'native'
      uses: actions/upload-artifact@v1
      with:
        name: helloworld-${{ matrix.os }}
        path: helloworld
    - name: Stash (Non-Native)
      if: matrix.true-os == 'dos'
      uses: actions/upload-artifact@v1
      with:
        name: helloworld-${{ matrix.true-os }}
        path: helloworld
